### ISSUE TITLE
文面を見直す

### ISSUE THREAD

**Issue by takahashim** [aozorahack/aozorahack.github.io#3]
去年配布したチラシをベースに作ったため、その後の変更点が反映されていません。
OSC 2016 Tokyo/Springまでに内容を見直したいです。

**Comment by kskktk** [comment]
おおお。ということはチラシも作り直しですかね……

**Comment by takahashim** [comment]
@kskktk とりあえずチラシにあった「来年の夏には本の未来基金の大きなイベントを考えており」は「2016年の夏には〜」に変更してあります。
あと「今後は月イチのミーティングを考えています」はどうしますかね…（この機会に始めても良いとは思いました）。

**Comment by takahashim** [comment]
OSCも終わったんで、こちらは閉じておきます。
また何かあれば新しいissue作っていただければ。
